<VideoScreen@MDScreen>:
    name: "vid_screen"
    id : vid_screen
    on_leave : print("leaving..");video_player.state = 'stop'
    MDBoxLayout:
        orientation: "vertical"
        id: vid_box
        VideoPlayer:
            id : video_player 
            no_cache : False
            options: {'allow_stretch': True}
            #thumbnail : "https://www.regione.sardegna.it/media/thumbnails/360/17_158_20080630092633.jpg"
            